# Generated by Django 4.0.5 on 2022-06-16 11:50

import DiplomaSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('number_slide', models.IntegerField()),
                ('original_file', models.FileField(upload_to=DiplomaSite.models.uploadmodel_file_upload_to)),
                ('segm_file', models.FileField(upload_to=DiplomaSite.models.uploadmodel_file_upload_to)),
                ('name_pacient', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
